title: Rubin Observatory Raw Data File Format
handle: CTN-004
site_url: https://ctn-004.lsst.io/
date: 2025-08-12
abstract: |-
  At the NSF-DOE Vera C. Rubin Observatory we write data from the LSSTCam and
  LATISS instruments using FITS format with one file written per detector. Here
  we discuss the layout of those FITS files and describe the FITS headers.
doi: 10.71929/rubin/3011115
osti_id: 3011115
authors:
- jennesst
- johnsonas
relationships:
  Cites:
  - 10.1051/0004-6361/201015362
  - 10.1117/12.2629569
  - 10.48550/arXiv.1201.1336
  - 10.71929/RUBIN/2561361
  - 10.71929/rubin/2570536
  - 10.71929/rubin/2570545
  - 10.71929/rubin/2571927
  - 10.71929/rubin/2571930
