title: 'The Monster: A reference catalog with synthetic ugrizy-band fluxes for the
  Vera C. Rubin observatory'
handle: DMTN-277
site_url: https://dmtn-277.lsst.io/
date: 2025-05-09
abstract: |-
  In order to facilitate bootstrap photometric calibrations of early Rubin
  Observatory data we have created an all sky reference catalog called The
  Monster.  This reference catalog uses a rank-ordered set of other reference
  catalogs to generate synthetic ugrizy-band fluxes that can be used calibrate
  images processed with the LSST science pipelines. This document describes the
  methodology used to create The Monster, documents the input external reference
  catalogs, and performs basic data validation of the first version of The
  Monster.
doi: 10.71929/rubin/2583688
osti_id: 2583688
authors:
- fergusonps
- rykoffe
- carlinjl
- saundersc
- parejkojk
relationships:
  References:
  - 10.1017/pasa.2019.27
  - 10.1051/0004-6361/202243709
  - 10.1051/0004-6361/202243940
  - 10.1093/mnras/stv1130
  - 10.3847/1538-3881/aa9f22
  - 10.3847/1538-4357/aae386
  - 10.3847/1538-4365/ab929e
  - 10.3847/1538-4365/ac00b3
  - 10.48550/arXiv.1612.05560
  - 10.48550/arXiv.2305.01695
