title: The MultiProFit astronomical source modelling code
handle: DMTN-312
site_url: https://dmtn-312.lsst.io/
date: 2025-05-21
abstract: |-
  This note describes the MultiProFit astronomical source modelling code, and
  particularly its development and use for modelling coadded objects in the LSST
  Science Pipelines.
doi: 10.71929/rubin/2584108
osti_id: 2584108
authors:
- taranuds
relationships:
  References:
  - 10.1007/978-0-387-40065-5
  - 10.1086/671228
  - 10.1093/mnras/stw3039
  - 10.21105/joss.02338
  - 10.71929/rubin/2570545
  IsReferencedBy:
  - 10.71929/rubin/2570536
