title: Review of Timeseries Features
handle: DMTN-118
site_url: https://dmtn-118.lsst.io/
date: 2021-05-28
abstract: |-
  Rubin Observatory will compute timeseries variability features on lightcurves
  to aid users in identifying objects of interest, both during realtime Alert
  Production as well as in the annual Data Releases. The Data Products
  Definition Document (DPDD; LSE-163) allocates space for pre-computed
  timeseries features, and a sample set is baselined in LDM-151. However, in the
  subsequent decade the scientfic community has made a great deal of further
  progress in this area. This technote reviews the relevant literature, grouping
  related features where possible; discusses potential concerns and open
  questions; and proposes a new baseline feature set.
doi: 10.71929/rubin/2997999
osti_id: 2997999
authors:
- bellme
relationships:
  References:
  - 10.1007/BF00648343
  - 10.1016/j.ascom.2016.05.006
  - 10.1016/j.ascom.2017.12.001
  - 10.1038/s41550-017-0321-z
  - 10.1046/j.1365-8711.1999.02667.x
  - 10.1051/0004-6361/201116898
  - 10.1051/0004-6361/201322648
  - 10.1051/0004-6361/201323252
  - 10.1051/0004-6361/201527188
  - 10.1051/0004-6361/201628700
  - 10.1051/0004-6361/201935276
  - 10.1051/0004-6361/201936905
  - 10.1051/0004-6361/202039193
  - 10.1051/0004-6361:20020258
  - 10.1051/0004-6361:20020802
  - 10.1051/0004-6361:20034578
  - 10.1051/0004-6361:20066930
  - 10.1051/0004-6361:200811296
  - 10.1051/epjconf/201715203001
  - 10.1086/116556
  - 10.1086/133808
  - 10.1086/156444
  - 10.1086/160554
  - 10.1086/171844
  - 10.1086/176050
  - 10.1086/178188
  - 10.1086/303600
  - 10.1086/339856
  - 10.1086/341707
  - 10.1086/376598
  - 10.1086/506198
  - 10.1086/512054
  - 10.1086/588518
  - 10.1086/605984
  - 10.1086/657607
  - 10.1086/664960
  - 10.1088/0004-6256/141/3/93
  - 10.1088/0004-637X/733/1/10
  - 10.1088/0004-637X/735/2/68
  - 10.1088/0004-637X/738/2/162
  - 10.1088/0004-637X/756/1/67
  - 10.1088/0004-637X/763/1/32
  - 10.1088/0004-637X/764/2/167
  - 10.1088/0004-637X/771/1/9
  - 10.1088/0004-637X/812/1/18
  - 10.1088/0004-637X/814/1/35
  - 10.1088/0067-0049/203/2/32
  - 10.1088/1538-3873/aaa753
  - 10.1088/1538-3873/ab1597
  - 10.1088/1538-3873/ab1609
  - 10.1088/1538-3873/ab26f1
  - 10.1088/2041-8205/811/2/L34
  - 10.1093/mnras/203.4.917
  - 10.1093/mnras/241.2.153
  - 10.1093/mnras/stab1502
  - 10.1093/mnras/sts412
  - 10.1093/mnras/sts650
  - 10.1093/mnras/stt1206
  - 10.1093/mnras/stt1264
  - 10.1093/mnras/stt2499
  - 10.1093/mnras/stu2274
  - 10.1093/mnras/stu372
  - 10.1093/mnras/stv1816
  - 10.1093/mnras/stv2333
  - 10.1093/mnras/stw2262
  - 10.1093/mnras/stx2570
  - 10.1093/mnras/stx3222
  - 10.1093/mnras/sty838
  - 10.1093/mnras/stz2448
  - 10.1093/mnras/stz2711
  - 10.1093/mnras/stz444
  - 10.1093/mnras/stz844
  - 10.1093/mnrasl/slw002
  - 10.1109/TSP.2012.2204260
  - 10.1111/j.1365-2966.2006.10049.x
  - 10.1111/j.1365-2966.2008.12689.x
  - 10.1111/j.1365-2966.2011.18514.x
  - 10.1111/j.1365-2966.2011.18575.x
  - 10.1111/j.1365-2966.2011.19768.x
  - 10.1111/j.1365-2966.2011.20119.x
  - 10.1515/9781400848911
  - 10.3847/0004-637X/817/1/73
  - 10.3847/0004-637X/826/2/118
  - 10.3847/0067-0049/225/2/31
  - 10.3847/1538-3881/aa8fd3
  - 10.3847/1538-3881/aadfd8
  - 10.3847/1538-3881/ab1f46
  - 10.3847/1538-3881/ab3a2f
  - 10.3847/1538-3881/ab5182
  - 10.3847/1538-3881/abc1e2
  - 10.3847/1538-3881/abd5c1
  - 10.3847/1538-4357/ab418c
  - 10.3847/1538-4357/abc6fd
  - 10.3847/1538-4365/aab761
  - 10.3847/1538-4365/aab766
  - 10.3847/1538-4365/aab77c
  - 10.3847/1538-4365/aab781
  - 10.48550/arXiv.1506.00010
  - 10.48550/arXiv.1709.06257
  - 10.48550/arXiv.astro-ph/0012143
  - 10.48550/arXiv.astro-ph/0106474
  - 10.5281/zenodo.592747
  - 10.71929/rubin/2587108
  - 10.71929/rubin/2587118
  - 10.71929/rubin/2997573
  IsReferencedBy:
  - 10.71929/rubin/2998097
