title: Astrometric Calibration in the LSST Pipeline
handle: DMTN-266
site_url: https://dmtn-266.lsst.io/
date: 2024-10-02
abstract: |-
  We describe our procedure for fitting an astrometric solution in the LSST Data
  Release Production.
doi: 10.71929/rubin/2583846
osti_id: 2583846
authors:
- saundersc
relationships:
  References:
  - 10.1051/0004-6361/202140463
  - 10.1051/0004-6361/202243940
  - 10.1088/1538-3873/aa6c55
  - 10.3847/1538-3881/ac0722
  - 10.71929/rubin/2570545
  - 10.71929/rubin/2583688
