title: Vera C. Rubin Observatory Prompt Products
site_url: https://prompt-products.lsst.io
date: 2025-02-24
abstract: |-
  Descriptive text.
  Mention that the dataset continues to grow as we observe the Legacy Survey
  of Space and Time.
instrument_doi: 10.71929/rubin/2571927
description_paper: 10.71929/rubin/3019817
dataset_types:
- abstract: |-
    Measurements for 5-sigma source detections in difference images that were
    issued to the community brokers.
  path: products/alerts/index.html
  misc:
    name: alert packets
    format: application/avro
