title: 'Survey Strategy: Rolling Cadence'
handle: PSTN-052
site_url: https://pstn-052.lsst.io/
date: 2021-06-27
abstract: |-
  We cover the basics of how a rolling cadence survey strategy can work, and
  review the results of a variety of rolling simulations. We find that Type Ia
  SNe recovery can be enhanced by using rolling cadence, while detecting fast
  microlensing events are dominated by footprint coverage.
doi: 10.71929/rubin/2584109
osti_id: 2584109
authors:
- yoachimp
