title: Study of the Photon Transfer Curve in the CCD detectors of the Vera C.
  Rubin Observatory
handle: RTN-056
site_url: https://rtn-056.lsst.io/
date: 2023-04-04
abstract: |-
  The RECA internship program provides Colombian students with an opportunity to
  enhance their research skills in Astronomy, Astrophysics, and Cosmology.
  During this three-month program, our main objective was to study the Photon
  Transfer Curves (PTC) of the Vera C. Rubin Observatory, specifically the gain,
  and to compare it with the gain obtained through pairs of flats.  Overall, the
  study of PTCs is crucial in understanding the performance of detectors and
  instruments used in Astronomy. The Vera C. Rubin Observatory is an important
  facility that will enable researchers to carry out a wide range of studies in
  this field, making it essential to investigate its gain performance.  We used
  run 13144 to construct the PTCs and 13186 to analyze the crosstalk. We
  employed the LSST Science Pipelines (also known as the DM stack), a software
  under development for this observatory, which performs all the necessary
  reductions for the construction of the PTCs. We also used simulations to
  replicate the observed effects.  Initially, we found a 5% difference between
  the gain calculated by PTC and pairs of flats for a flow range between 5000
  and 10000 ADU. Simulations showed that this difference was due to the handling
  of statistics and the assumption that the distribution following the Lupton
  equation is Gaussian. We found an error interval for this flow region based on
  the vendor, with (1.8 ± 0.7, 4.1 ± 0.9) % for E2V and (0.85 ± 0.7, 2.2 ± 0.9)
  % for ITL. From the PTC, we also obtained the average Full Well Capacity of
  LSSTCam as 130000 ± 10000$ electrons.  We identified a list of segments where
  we found differences with the results obtained by SLAC National Acceleration
  Laboratory in PTC parameters, low saturation level, or other defects. We
  detected and corrected the effect of statistics in the gain calculation using
  pairs of flats and proposed a code change, which was implemented in the
  pipeline software. We do not recommend correcting for crosstalk as it does not
  significantly affect the parameters and does not change the shape of the PTC.
  However, the opposite is true for the nonlinearity correction.
doi: 10.71929/rubin/2575156
osti_id: 2575156
authors:
- giraldoml
- calderonj
- plazasa
- lagecs
relationships:
  References:
  - 10.1038/s41586-020-2649-2
  - 10.1051/0004-6361/201935508
  - 10.1088/1748-0221/10/05/C05010
  - 10.1088/1748-0221/10/05/C05015
  - 10.1088/1748-0221/12/03/C03091
  - 10.1088/1748-0221/9/04/C04023
  - 10.1117/12.2314269
  - 10.1117/12.2562915
  - 10.1117/12.670615
  - 10.1117/12.671457
  - 10.1146/annurev-astro-081710-102545
  - 10.3847/1538-3881/aabc4f
  - 10.3847/1538-3881/aac08d
  - 10.3847/1538-4357/ab042c
  - 10.48550/arXiv.0912.0201
  - 10.71929/rubin/2570545
  - 10.71929/rubin/2571927
  - 10.71929/rubin/2575154
  IsReferencedBy:
  - 10.71929/rubin/2575154
