title: Unrecognized Blends in LSSTComCam Data Preview 1 ECDFS
handle: SITCOMTN-128
site_url: https://sitcomtn-128.lsst.io/
abstract: |-
  Unrecognized blends are a class of blended objects where two (or more)
  objects are so close on the sky that they are mistakenly identified as a
  single object. These objects can cause a variety of issues for science and
  simple validation. We can identify such objects by using higher resolution
  imaging from a space based telescope that will not be affected by ground
  based seeing and then label detected objects as isolated, recognized blends,
  or unrecognized blends. We find that for objects with 23 < i < 24.5, 18% of
  objects are unrecognized blends.
date: 2025-07-01
doi: 10.71929/rubin/2570850
osti_id: 2570850
authors:
- adarip
- lindena
relationships:
  Cites:
  - 10.3847/0004-637x/816/1/11
  - 10.1086/176071
  - 10.1088/0067-0049/197/2/35
  - 10.1088/0067-0049/197/2/36
  - 10.1088/0067-0049/207/2/24
  - 10.1038/s41592-019-0686-2
  - 10.1093/mnras/stad664
  - 10.1088/0004-637x/805/2/121
  - 10.71929/rubin/2570536
  - 10.71929/RUBIN/2561361
  - 10.71929/RUBIN/2570324
  - 10.5281/zenodo.5683848
  - 10.48550/arXiv.2503.16680
